language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Miniball"); Pkg.test("Miniball"; coverage=true)'
